### PR TITLE
Few stylistic/editorial suggestions

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
ping :)

**Comment by yoavweiss** [comment]
Is it possible to break out the long lines so that review would be easier in the future? Otherwise, LGTM

**Comment by Wilto** [comment]
Argh, completely missed the notification on this! I’ll give it a read/merge today.

**Comment by marcoscaceres** [comment]
I find it helps to turn of soft wrapping in GH. It's not practical to wrap
lines in BS ... Unless we settle on a command line tool? Any suggestions?

**Comment by marcoscaceres** [comment]
I'll have to rebase this

**Comment by marcoscaceres** [comment]
Rebased ...

**Comment by tabatkins** [comment]
>  It's not practical to wrap lines in BS ... 

(Interestingly, you turning off soft-wrapping in GH made the above blockquote look stupid, because there was a hard break between "wrap" and "lines" that I had to remove.)

What do you mean by this?  Look at any Bikeshed file I or fantasai edit - we wrap lines consistently (using [semantic line breaks](http://rhodesmill.org/brandon/2012/one-sentence-per-line/), which are better both for editting and for diffing).

**Comment by marcoscaceres** [comment]
Ok, very valid point @tabatkins ... just needs a bit of a shift in thinking to "semantic line breaks" (and that all the editors agree to this!). The document is currently not written like that tho - so that will require someone to actually go through the whole thing and place breaks in natural places.

**Comment by marcoscaceres** [comment]
(I'm happy to do that, btw... but can we please merge this ... it's been like 10 days and feeling unloved :( )

**Comment by Wilto** [comment]
Oh, @marcoscaceres, you can totally feel free to merge changes—this doc is in a major state of flux, so feel free to self-merge when things get +1’d.

**Comment by marcoscaceres** [comment]
@Wilto thanks! will do.

**Comment by tabatkins** [comment]
> Ok, very valid point @tabatkins ... just needs a bit of a shift in thinking to "semantic line breaks" (and that all the editors agree to this!).

I just suggested semantic linebreaks as a good way to do your linebreaking.  Still curious what you meant by 

> It's not practical to wrap lines in BS ...

though.

**Comment by marcoscaceres** [comment]
@tabatkins, imagine I found a bug in the middle of a sentence but no semantic wrapping had been used - rather lines had been hand broken at around 80 cols. Trying to add new text in such situations becomes a huge pain (as described in the link you sent) 

In other specs, I've always coped with this by forcing contributors to run HTML through HTML5 tidy. I'm not suggesting we do this here (because BS is not actually HTML, hence Tidy would just make a mess of things: hence "It's not practical to [computationally?] wrap lines in BS "). I was merely asking what our line breaking strategy would be (given that it has to be done manually).

**Comment by tabatkins** [comment]
Ah, ok, so your reference to "not practical" was "not practical to enforce with existing tooling".  Cool.

**Comment by marcoscaceres** [comment]
exactly, sorry about the confusion!

**Comment by marcoscaceres** [comment]
(btw, I really like the semantic line break idea... It's a great natural fit for BS!)

**Pull request merged**
