### PR TITLE
Fixing the HTML merge errors

### PR DESCRIPTION
**Pull request by OrganicPanda**
I noticed the [HTML](https://responsiveimagescg.github.io/eq-usecases/) had, what looked like, git merge problems so I re-ran the bikeshed process.

``` shell
curl https://api.csswg.org/bikeshed/ -F file=@index.bs -F force=1 > index.html
```

I've never used bikeshed before so I'm not sure if that's exactly right but it looks ok.

Hope that helps - keep up the good work!

### CODE REVIEW

**Comment by yoavweiss** [comment]
@wilto - can you take a look?

**Comment by Wilto** [comment]
Will do.

**Comment by marcoscaceres** [comment]
LGTM... seems someone merged a merge conflict.

**Comment by Wilto** [comment]
cough

**Pull request merged**
